export const servicesData = [
  {
    category: "Reformas",
    title: "Instalador de piso",
    description:
      "Porcelanato, vinílico, laminado e carpete. Fino acabamento e prazo garantido.",
    provider: "Piso Certo",
    providerInitials: "PC",
    rating: "4.8",
    reviews: "97",
    price: "R$45",
    unit: "por m²",
    badge: "verificado",
    cover: "bg-[#f0e8dc]",
    icon: "🔨",
    starsFilled: 5,
  },
  {
    category: "Aulas",
    title: "Aulas de inglês online",
    description:
      "Inglês conversacional para iniciantes e avançados. 1h/aula com material incluso.",
    provider: "Profa. Luana",
    providerInitials: "PL",
    rating: "5.0",
    reviews: "62",
    price: "R$60",
    unit: "por hora",
    badge: "",
    cover: "bg-[#dde4f5]",
    icon: "📚",
    starsFilled: 5,
  },
  {
    category: "Encanamento",
    title: "Encanador 24h",
    description:
      "Vazamentos, desentupimentos, troca de registros e torneiras. Urgência atendida.",
    provider: "Roberto Hidra",
    providerInitials: "RH",
    rating: "4.8",
    reviews: "156",
    price: "R$120",
    unit: "por visita",
    badge: "verificado",
    cover: "bg-[#e8ddf0]",
    icon: "🔧",
    starsFilled: 5,
  },
  {
    category: "Jardinagem",
    title: "Dedetização e controle de pragas",
    description:
      "Cupins, baratas, formigas e ratos. Garantia de 60 dias com certificado.",
    provider: "Dedet Rio",
    providerInitials: "DR",
    rating: "4.8",
    reviews: "120",
    price: "R$200",
    unit: "por serviço",
    badge: "verificado",
    cover: "bg-[#ddf0e2]",
    icon: "🌿",
    starsFilled: 5,
  },
  {
    category: "Limpeza",
    title: "Limpeza pós-obra",
    description:
      "Especializada em remoção de pó de obra, argamassa e resíduos de construção.",
    provider: "Clean Pro",
    providerInitials: "CP",
    rating: "4.7",
    reviews: "84",
    price: "R$280",
    unit: "por serviço",
    badge: "",
    cover: "bg-[#d8edf5]",
    icon: "🧹",
    starsFilled: 4,
  },
]
