export const servicesData = [
  {
    category: "REFORMAS",
    title: "Instalador de piso",
    description: "Porcelanato, vinílico, laminado e carpete. Fino acabamento.",
    provider: "Piso Certo",
    providerInitials: "PC",
    rating: "4.8",
    reviews: "97",
    price: "R$45",
    unit: "/m²",
    badge: "verificado",
    cover: "bg-[#d6d4e8]",
    icon: "🪜",
  },
  {
    category: "AULAS",
    title: "Aulas de inglês online",
    description: "Inglês conversacional para iniciantes e avançados. 1h/aula.",
    provider: "Profa. Luana",
    providerInitials: "PL",
    rating: "5.0",
    reviews: "62",
    price: "R$60",
    unit: "/hora",
    badge: "",
    cover: "bg-[#bee7eb]",
    icon: "📚",
  },
  {
    category: "ENCANAMENTO",
    title: "Encanador 24h",
    description: "Vazamentos, desentupimentos, troca de registros e torneiras.",
    provider: "Roberto Hidra",
    providerInitials: "RH",
    rating: "4.8",
    reviews: "156",
    price: "R$120",
    unit: "/visita",
    badge: "verificado",
    cover: "bg-[#cad8ec]",
    icon: "🔧",
  },
  {
    category: "JARDINAGEM",
    title: "Dedetização e controle de pragas",
    description: "Cupins, baratas, formigas e ratos. Garantia de 60 dias.",
    provider: "Dedet Rio",
    providerInitials: "DR",
    rating: "4.6",
    reviews: "120",
    price: "R$200",
    unit: "/serviço",
    badge: "verificado",
    cover: "bg-[#d0ebd7]",
    icon: "🌿",
  },
  {
    category: "LIMPEZA",
    title: "Limpeza pós-obra",
    description: "Especializada em remoção de pó de obra, argamassa e resíduos.",
    provider: "Clean Pro",
    providerInitials: "CP",
    rating: "4.7",
    reviews: "64",
    price: "R$280",
    unit: "/serviço",
    badge: "",
    cover: "bg-[#bee5eb]",
    icon: "🧹",
  },
]
